blank_issues_enabled: false
contact_links:
  - name: I have a performance issue
    url: https://devtools.vuejs.org/guide/devtools-perf.html
    about: Follow the guide to share performance profiling data with us!
  - name: Questions & Discussions
    url: https://github.com/vuejs/devtools/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  - name: Discord Chat
    url: https://chat.vuejs.org
    about: Ask questions and discuss with other Vue users in real time.
  - name: GitHub Sponsor
    url: https://github.com/sponsors/Akryum
    about: Love the Vue devtools? Please consider supporting us via GitHub sponsors.
